### ISSUE TITLE
errors in Unity 2020.LTS and above

### ISSUE THREAD

**Issue by antigollos** [joaen/EasyIK#2]
Simply doesn't work in Unity 2020 LTS and above. As soon as you attach the script it starts throwing constant errors. A pity that such great stuff is not  supported. To put it on github doesn't make it better, because no one cares, and I can't do it, since I am not a programmer.

**Comment by joaen** [comment]
Hi! I just tested the script in Unity 2019.4.34f1 LTS, 2021.3.11f1 LTS and 2020.3.41f1 LTS without encountering any errors. Can you perhaps share some more details. What are you trying to do, what kind of errors are you getting and which version of Unity are you using?

**Comment by antigollos** [comment]
> Hi! I just tested the script in Unity 2019.4.34f1 LTS, 2021.3.11f1 LTS and 2020.3.41f1 LTS without encountering any errors. Can you perhaps share some more details. What are you trying to do, what kind of errors are you getting and which version of Unity are you using?

Idk why, but I copied your script back to my project and now I don't get any errors: Same project, same unity version O_O Unity is such a crap! However, I noticed the script only works in play mode, which doesn't help me to animate within timeline, which runs in editor mode. And as far as I know the script must support timeline as well, if I want to record things there. Also, can't connect a whole human mesh blindly and see in play mode if it works. 

And since I don't have great expectations that any github project for Unity on this world gets expanded - because that happens too seldom, I would like to thank you and wish all the best.

**Comment by joaen** [comment]
No worries! If you put `[ExecuteInEditMode]` at the start of the script you should be able to run it in the editor. 
![image](https://user-images.githubusercontent.com/6629861/197621054-7441169a-5998-40ae-b243-3e72c475e968.png)

**Comment by antigollos** [comment]
Again errors when attaching the script to any bones! I don't want anymore. No tutorials, no nothing! 12 years with an engine that is only crap today and has the workflow from a tool from 1998. Moving the mouse in 2021.x LTS is a crime already, without having a pop up that tells me to wait until unity re-initializes/or draws its UI.

FUCK UNITY!!! 

Thanks for everything!
